"""news

Revision ID: 0f9d688f4096
Revises: 5dd567c215fb
Create Date: 2024-12-12 12:52:57.069962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9d688f4096'
down_revision: Union[str, None] = '5dd567c215fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'study_direction_instructor_relatinoship', ['study_direction_ref_id', 'instructor_ref_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_direction_instructor_relatinoship', type_='unique')
    op.drop_column('news', 'is_hidden')
    # ### end Alembic commands ###
