"""init

Revision ID: 443b689475e1
Revises: 
Create Date: 2024-12-12 11:06:52.623827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443b689475e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bucket', sa.String(length=32), nullable=False),
    sa.Column('file_key', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'DOCUMENT', name='mediatype'), nullable=False),
    sa.Column('photo_codec', sa.Enum('JPG', 'PNG', name='photocodec'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.CheckConstraint("(media_type != 'PHOTO' AND photo_codec IS NULL) OR (media_type = 'PHOTO' AND photo_codec IS NOT NULL)"),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_updated_at'), 'media', ['updated_at'], unique=False)
    op.create_table('news',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_updated_at'), 'news', ['updated_at'], unique=False)
    op.create_table('announcements',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('media_ref_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.CheckConstraint('index >= 0'),
    sa.ForeignKeyConstraint(['media_ref_id'], ['media.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id'),
    sa.UniqueConstraint('index')
    )
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcements_updated_at'), 'announcements', ['updated_at'], unique=False)
    op.create_table('instructors',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('seniority', sa.Interval(), nullable=False),
    sa.Column('media_ref_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['media_ref_id'], ['media.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_instructors_created_at'), 'instructors', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructors_updated_at'), 'instructors', ['updated_at'], unique=False)
    op.create_table('news_gallery',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('news_ref_id', sa.Uuid(), nullable=False),
    sa.Column('media_ref_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.CheckConstraint('index >= 0 AND index < 10'),
    sa.ForeignKeyConstraint(['media_ref_id'], ['media.ref_id'], ),
    sa.ForeignKeyConstraint(['news_ref_id'], ['news.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id'),
    sa.UniqueConstraint('news_ref_id', 'index')
    )
    op.create_index(op.f('ix_news_gallery_created_at'), 'news_gallery', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_gallery_updated_at'), 'news_gallery', ['updated_at'], unique=False)
    op.create_table('study_directions',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('icon_ref_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['icon_ref_id'], ['media.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_study_directions_created_at'), 'study_directions', ['created_at'], unique=False)
    op.create_index(op.f('ix_study_directions_updated_at'), 'study_directions', ['updated_at'], unique=False)
    op.create_table('study_programs',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('direction_ref_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('document_ref_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['direction_ref_id'], ['study_directions.ref_id'], ),
    sa.ForeignKeyConstraint(['document_ref_id'], ['media.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_study_programs_created_at'), 'study_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_study_programs_updated_at'), 'study_programs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_programs_updated_at'), table_name='study_programs')
    op.drop_index(op.f('ix_study_programs_created_at'), table_name='study_programs')
    op.drop_table('study_programs')
    op.drop_index(op.f('ix_study_directions_updated_at'), table_name='study_directions')
    op.drop_index(op.f('ix_study_directions_created_at'), table_name='study_directions')
    op.drop_table('study_directions')
    op.drop_index(op.f('ix_news_gallery_updated_at'), table_name='news_gallery')
    op.drop_index(op.f('ix_news_gallery_created_at'), table_name='news_gallery')
    op.drop_table('news_gallery')
    op.drop_index(op.f('ix_instructors_updated_at'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_created_at'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_announcements_updated_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_news_updated_at'), table_name='news')
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_media_updated_at'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
