"""relationship

Revision ID: 5dd567c215fb
Revises: 17d9ea50d812
Create Date: 2024-12-12 11:30:48.543030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd567c215fb'
down_revision: Union[str, None] = '17d9ea50d812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_direction_instructor_relatinoship',
    sa.Column('study_direction_ref_id', sa.Uuid(), nullable=False),
    sa.Column('instructor_ref_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_ref_id'], ['instructors.ref_id'], ),
    sa.ForeignKeyConstraint(['study_direction_ref_id'], ['study_directions.ref_id'], ),
    sa.PrimaryKeyConstraint('study_direction_ref_id', 'instructor_ref_id'),
    sa.UniqueConstraint('study_direction_ref_id', 'instructor_ref_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_direction_instructor_relatinoship')
    # ### end Alembic commands ###
