"""reviews

Revision ID: c081d233c254
Revises: 0f9d688f4096
Create Date: 2024-12-12 13:17:03.019342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c081d233c254'
down_revision: Union[str, None] = '0f9d688f4096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_direction_reviews',
    sa.Column('ref_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('direction_ref_id', sa.Uuid(), nullable=False),
    sa.Column('program_ref_id', sa.Uuid(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5'),
    sa.ForeignKeyConstraint(['direction_ref_id'], ['study_directions.ref_id'], ),
    sa.ForeignKeyConstraint(['program_ref_id'], ['study_programs.ref_id'], ),
    sa.PrimaryKeyConstraint('ref_id')
    )
    op.create_index(op.f('ix_study_direction_reviews_created_at'), 'study_direction_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_study_direction_reviews_updated_at'), 'study_direction_reviews', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_direction_reviews_updated_at'), table_name='study_direction_reviews')
    op.drop_index(op.f('ix_study_direction_reviews_created_at'), table_name='study_direction_reviews')
    op.drop_table('study_direction_reviews')
    # ### end Alembic commands ###
